#require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2

  NewCops: enable

  # additional excludes for Rails
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'log'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A#']

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'routes/*.rb'

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: false

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EndlessMethod:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: false

Style/MultilineInPatternThen:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/StringChars:
  Enabled: false

Style/SwapValues:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Bundler/GemVersion:
  Enabled: true
