flood: ["Channel for flood", "Channel for flood"]
leaves: ["", ""]
general: ["General team discussions and announcements.", "The main channel for all general discussions and announcements. Use it to share important information that concerns the whole team."]
issues: ["Tracking and resolving team issues.", "A channel for tracking and resolving team issues. Report any problems and find solutions here."]
suggestions: ["", ""]
game_rules: ["", ""]
